### ISSUE TITLE
Changes to MediaConfigurations cannot be feature detected in older UAs.

### ISSUE THREAD

**Issue by jernoble** [w3c/media-capabilities#111]
When a change is made to `MediaConfigurations` (e.g., the addition of `keySystemConfiguration` to `MediaDecodingConfiguration`), this change cannot necessarily be feature detected when passed to older implementations of `MediaCapabilities`.

To take a completely made up (and ridiculous) example, imagine that the following IDL was added to `MediaConfiguration`:

```
partial interface AudioConfiguration {
   bool volumeGoesTo11;
};
```

Clients who make the following call:

```
navigator.mediaCapabilities.decodingInfo(
    {audioConfiguration: {type: "file", contentType: "audio/aac", volumeGoesTo11: true }}
).then(info => {
        if (info.supported) {
            audio.volume = 11;
            audio.play();
        } else {
            attachWebAudioGainNode();
            audio.play();
        }
    });
```

...can't distinguish between UAs who support the new `volumeGoesTo11` configuration property and do support the property's value, and those who don't support the property.

**Comment by jernoble** [comment]
One possible spec change which would make all future changes feature detectable would be to take a hint from the Encrypted Media Extensions spec, specifically the [getConfiguration()](https://w3c.github.io/encrypted-media/#dom-mediakeysystemaccess-getconfiguration) method on `MediaKeySystemAccess`, which returns the configuration options which led to its creation.

Bikeshedding, the spec might have some language like that of EME in the [Create a MediaCapabilitiesInfo](https://wicg.github.io/media-capabilities/#create-media-capabilities-info) algorithm, like (hand wavy) "For each supported value in _configuration_, set the same value in _supported configuration_." and expose that _supported configuration_ on `MediaCapabilitiesInfo`. Such a change may look something like:

```
partial interface MediaCapabilitiesInfo {
    MediaConfiguration supportedConfiguration;
};
```

And with that change in place, the above example would look more like:
```
navigator.mediaCapabilities.decodingInfo(
    {audioConfiguration: {type: "file", contentType: "audio/aac", volumeGoesTo11: true }}
).then(info => {
        if (info.supported && typeof info.supportedConfiguration.volumeGoesTo11 !== 'undefined') {
            audio.volume = 11;
            audio.play();
        } else {
            attachWebAudioGainNode();
            audio.play();
        }
    });
```

**Comment by chcunningham** [comment]
I like it. My only thought is the interface may need to be adjusted depending on the outcome of #102. Do you think we should block on that?

**Comment by chcunningham** [comment]
> Do you think we should block on that?

Just pinged @joeyparrish internally. @mwatson2 FYI

**Comment by jernoble** [comment]
Just a thought: this may require a new dictionary, `MediaCapabilitiesEncodingInfo`, so that we could do the following:

```
interface MediaCapabilitiesEncodingInfo : MediaCapabilitiesInfo {
    MediaEncodingConfiguration supportedConfiguration;
};
```

**Comment by jernoble** [comment]
Regardless of how we define the "transition" API, there's a clear need for this for the non-transition case, so I don't think we should treat that API as blocking this one.

**Comment by mounirlamouri** [comment]
There is still a case where the two APIs would conflict: if we need to expose an array of configurations instead of only one.
