### ISSUE TITLE
No need to link to both HTML LS and HTML 5.x

### ISSUE THREAD

**Issue by svgeesus** [w3c/media-capabilities#116]
The [normative references](https://wicg.github.io/media-capabilities/#normative) lists both the HTML LS and also HTML 5.2.

Since [W3C and WHAT WG signed the MOU](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html), the HTML 5.2 reference should be deleted in the bikeshed source.

**Comment by chrisn** [comment]
This was fixed by @tidoust in 2294043c5bafa04bddae86aa545c8da64959a291.
