### ISSUE TITLE
Intent to Migrate: Media Capabilities

### ISSUE THREAD

**Issue by tidoust** [w3c/media-capabilities#117]
## Intent to Migrate: Media Capabilities

Hi all, cc @mounirlamouri @jernoble as chairs of the Media Working Group. The recently created [Media Working Group](https://www.w3.org/media-wg/) is ready to adopt Media Capabilities as a W3C Recommendation track deliverable.

Note some of the sections below need some love. I let people involved in the development of this proposal chime in as needed!

### Working group decision to adopt

See the [charter of the Media Working Group](https://www.w3.org/2019/05/media-wg-charter.html#deliverables)

### Proposal

Latest [Media Capabilities draft](https://wicg.github.io/media-capabilities/) ([Git repo](http://github.com/WICG/media-capabilities))

### Summary

An API to allow websites to make an optimal decision when picking media content for the user. The API exposes information about the decoding and encoding capabilities for a given format, but also about output capabilities to find the best match based on the device’s display.

### Motivation and Use Cases

Detailed in the [explainer](https://github.com/WICG/media-capabilities/blob/master/explainer.md)

### Compatibility Risk

> Please characterize how much we might regret standardizing this new feature were we to change or remove it in the future. If you don’t have a github repository, include in this email links to relevant discussions, or documentation about support for the feature on the Web.

### Ongoing technical constraints

Some capabilities depend on the underlying hardware but user agents need to integrate these constraints for media playback in any case. The proposal merely exposes information that user agents already know.

It is expected that the feature will be supported in all environments with some level of media playback (desktop, mobile, tablets, TV, etc.).

### Link to implementation experience and demos

> If your proposal has implementation experience or demos, please provide links, including common patterns in deployed libraries. Otherwise, indicate if there are none.

### Data

No quantified data but most video publishing websites and most video player libraries currently implement heuristics to determine available capabilities. This proposal provides more satisfactory answers and should thus affect all users watching video on the Web, meaning quite a lot.

### Security and Privacy

See [responses to security and privacy questionnaire](https://github.com/WICG/media-capabilities/blob/master/security-privacy-questionnaire.md). Also see the [Security and Privacy Considerations](https://wicg.github.io/media-capabilities/#security-privacy-considerations) section in the latest draft

### Accessibility

No direct accessibility implications known at this stage. However, the proposal exposes technical decoding/encoding features (bitrate, resolution, etc.) for a format, some of which may be useful for accessibility (e.g. luminance characteristics of the screen). To be reviewed with accessibility team as the specification progresses along the recommendation track.

### Internationalization

No internationalization implications for the capabilities envisioned so far.

**Comment by marcoscaceres** [comment]
Requested Mozilla folks comment on the proposal https://github.com/mozilla/standards-positions/issues/182 

As WICG Chair, this the intent to migrate itself looks fine - thank you for preparing it. 

Thought the fingerprinting aspects remain, hopefully those will hopefully improve as standardization occurs. Let's give folks until 17th of June to comment. If there are not objections, happy for this to be transferred over.

**Comment by marcoscaceres** [comment]
Fixed date above... I meant July :) Can't believe it's July already!

**Comment by chcunningham** [comment]
Hi François. Thanks for preparing this. 

> Please characterize how much we might regret standardizing this new feature were we to change or remove it in the future...

Generally no concerns. The decodingInfo() API is now widely implemented and compat looks good. Of course, the spec is still a work in progress. We have some parts that are less mature, either because they're new (e.g. decodingInfo for encrypted media), or roughly proposed given low prioritization (Screen extensions, encodingInfo(), etc.). We'll continue to iterate post-migration.

> If your proposal has implementation experience or demos, please provide links, including common patterns in deployed libraries. Otherwise, indicate if there are none.

A demo of the decodingInfo() API can be found here.
https://googlechrome.github.io/samples/media-capabilities/decoding-info.html

Layout tests can also be instructive.
https://github.com/web-platform-tests/wpt/tree/master/media-capabilities

**Comment by marcoscaceres** [comment]
@tidoust, all, thanks again for preparing the intent to migrate. Kindly please move this over to the Media WG at your convenience. 

Just as reminder, once moved, the various bits of spec metadata that reference WICG will need changing.

**Comment by tidoust** [comment]
Thanks @marcoscaceres, repository has now been transferred to W3C and relevant info has been updated. I'm closing the issue accordingly.

@chcunningham Let me know if you spot any issue with the spec!
