### ISSUE TITLE
Add Support for Querying HDR & 4K Video Display Capabilities

### ISSUE THREAD

**Issue by vi-dot-cpp** [w3c/media-capabilities#119]
This is part 2, which covers display, of the HDR two-part series. Part 1 (#118) covers decoding and rendering. 

In addition to changes to `MediaCapabilities` proposed in #118, we propose the following edits to the Screen API. We are posting in `MediaCapabilities` first in order to incubate the idea and drive consensus. 

Add a query-based API – specifically for Video display capabilities – to the `Screen` API. This API aims solves the following problems: 
- Distinguish graphics and video capabilities #25 
    - Screen width/height issues #17 
    - Distinguish video rendering and screen support for color gamut #14,  
    - Display aspects of #10  
- The query-based approach addresses the following concerns: 
    - Finger printing – less readily available than static accessors
    - Static accessors are not capable of conveying HDR nuance [#110-comment ](https://github.com/WICG/media-capabilities/pull/110#issuecomment-467133392)

#### 1. Extend current Screen API to expose a Video attribute 
```
partial interface Screen { 
    [SameObject] readonly attribute Video video; 
}; 
```
#### 2. Add query-based API to Video Interface 
```
interface Video { 
    [NewObject] Promise<VideoInfo> displayInfo(VideoOutputConfiguration videoOutputConfiguration); 
}; 
```
#### 3.1 VideoOutputConfiguration dictionary 
```
dictionary VideoConfiguration { 
    required unsigned long width; 
    required unsigned long height; 
    HdrCapability hdrCapability;  // See #118
}; 
```
#### 4.1 VideoInfo dictionary 
```
dictionary VideoInfo { 
    required boolean supported; 
}; 
```
Team: @scottlow @gurpreetv @isuru-c-p @vi-dot-cpp from Microsoft

**Comment by chcunningham** [comment]
I repeat my [comment from #118](https://github.com/WICG/media-capabilities/issues/118#issuecomment-511077146) (I like it). attn other stake holders (apologies to anyone I've forgotten): @jernoble @eric-carlson @hober @jyavenard @padenot @mwatson2 @joeyparrish

**Comment by mwatson2** [comment]
[Please see my comment](https://github.com/WICG/media-capabilities/issues/118#issuecomment-511461132) on #119.

**Comment by jernoble** [comment]
Please see issue #110, which basically defines the same set of behavior.

**Comment by chcunningham** [comment]
> Please see issue #110, which basically defines the same set of behavior.

This basically picks up where that closed, moving those inputs and moved them onto Screen while addressed separate video-vs-graphics layer concerns about resolution.

**Comment by chcunningham** [comment]
> This basically picks up where that closed

Ah, I see its open :). What do you think about updating the PR with the ideas here? May want to wait for an outcome to the bucketing discussion in #118

**Comment by jernoble** [comment]
Totally fine with updating the PR to include `width` and `height` configuration properties. I can see the argument that some display devices may only be able to do certain HDR "modes" in certain resolutions.

**Comment by vi-dot-cpp** [comment]
Thanks everyone for the feedback. Please see [my update](https://github.com/WICG/media-capabilities/issues/118#issuecomment-512014384) in #118.

**Comment by vi-dot-cpp** [comment]
Per everyone's feedback, I [updated ](https://github.com/w3c/media-capabilities/issues/118#issuecomment-516231901)#118 and added the concept of `window.screen.video.displayInfo()` to pull request #124. Thanks, I appreciate it.

**Comment by chcunningham** [comment]
Closing old issue. Most of this discussion happened in #118. Lingering questions went to #135. And those are now mostly resolved by the changes to CSS, with open questions tracked in their repo https://github.com/w3c/csswg-drafts/issues/5044
