### ISSUE TITLE
Media WG contribution & engagement structure

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/media-capabilities#131]
Hey everyone, 

Gurpreet asked a valid question on our quick sync a few weeks back about the process of landing a PR. I thought it would be good to try and flush out process for the Media WG (since there doesn't seem to be a central Media WG repo; I'm putting it here for discussion). This is meant to be a **strawman proposal so please provide any feedback** - possibly a solid discussion to have at TPAC :)

## Proposal

1. **Telecon schedule:** Start off with monthly calls to keep things moving forward (we can increase this as necessary). @jernoble or @mounirlamouri should be able to set this up with our W3C contact François Daoust.

2. **Try to keep issues scoped to hopefully produce a single resolution:** When possible, if separate issues become apparent in an initial issue (eg: fingerprinting with regard to HDR) let’s spin up a new issue so tracking the discussion currently and for historical reasons is possible. This will also help keep the PRs simpler to review as well

3. **Formal consensus based resolutions:** We should have a solid & agreed upon process for recognizing consensus. The initial below is based on engagements in other WGs:

    a. On the call, consensus can be gained via individual proposed resolutions if there are no objections – within the IRC minutes it will be done with `PROPOSED RESOLUTION: <resolution>`, if no objections are raised this will change to `RESOLUTION: <resolution>` and will be added to the Github issue.

    b. If it is agreed that we’ll have 1 call per month, then we should have a Github based process as well (if the calls are more frequent, this may be less important):

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i. Github discussion occurs – as we gain agreement, the person expecting a resolution can follow the same above for their understanding of the resolutions. If there are no objections to those resolutions. At-mention editors of the spec at least or include all folks that have been engaged on the discussion.

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii. Create a PR based on the resolutions and have it reviewed by the editors and at least one other company not represented by the person submitting the PR or the editors. So let’s look at an example, Vi (Microsoft) is submitting a PR he will need a review by:
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. An editor, Mounir Lamouri or Chris Cunningham of Google
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Any other person that is not from Google or Microsoft

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iii. This allows 2 things, to ensure that the PR matches what everyone expected and the integrity of consensus

4. **WPT Plan with regards to spec changes:** I propose that a normative spec change (with author observable impacts) should spin up an issue within the WPT repo with an expectation of test changes being done by the spec modifier within a reasonable amount of time [should be defined by the group] of the spec change. Note: this sounds a bit harder than it actually is. Most of the normative changes are done in conjunction with an implementation plan by someone, at which point this will come along with the normal process of implementation and upstreaming of WPT tests.
        
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i. This has a great added benefit that someone that may not be aware of the change, or it’s low pri – they will start seeing a WPT testcase fail (assuming it is not an additive change) which will allow them to know that another browser has landed the change and interop issues have become possible and so they should prioritize an update to their implementation. This eases the burden on web developers bifurcation of code.

## Proposed Resolutions

So to follow my own recommendations - I'd like to propose the following resolutions to be added to the contribution file in each of the Media WG specifications:

1. **Proposed Resolution:** Have a formal W3 telecon once per month to discuss issues on the agenda from across the Media WG specifications (day & time to be determined following resolution)

2. **Proposed Resolution:** Try to keep issues scoped to a single specific topic and fork new issues to another issue

3. **Proposed Resolution:** Follow the formal based resolutions on the call asking for `Proposed Resolution: <resolution>` and if there are no objections, resolve by consensus and label in IRC as `Resolved: <resolution>`

4. **Proposed Resolution:** Formal based resolution on Github, outline the `Proposed Resolution: <resolution>` to require no objections on the issue thread after at-mentioning the editors & members involved in the discussion allowing 3 days to gauge consensus. Upon resolution, respond with comment of `Resolved: <resolution>`

5. **Proposed Resolution:** When submitting a PR to the spec add the editors as reviewers and one additional member that is not affiliated with either the company of the editors or your own company/organization.

6. **Proposed Resolution:** Upon PR merge, open a WPT issue to modify testcases if the normative change has author observable impact and have it addressed within 1 month of creation.

ccing editors of specs updated within the past year & media WG chairs: @mounirlamouri @beccahughes @beaufortfrancois @jernoble @chcunningham

**Comment by tidoust** [comment]
Just a couple of meta-comments:

> since there doesn't seem to be a central Media WG repo

The https://github.com/w3c/media-wg repo, which contains the group's home page, could perhaps be used as central Media WG repo for such pan-specifications discussions.

The public-media-wg@w3.org mailing-list is the only sure way to reach all WG participants in practice: participants are automatically added to the mailing-list when they join the group.


> Formal consensus based resolutions

Note the [Decision Policy](https://www.w3.org/2019/05/media-wg-charter.html#decisions) in the group's charter, which describes typical consensus building, and also sets some requirements to "afford asynchronous decisions and organizational deliberation".

**Comment by gregwhitworth** [comment]
Thanks @tidoust much apprecaited.

It seems I'm primarily trying to get a bit more firm on this with regards to asynchronous process, since all this work is done in GH:

> A call for consensus (CfC) will be issued for all resolutions

Effectively, get a bit more crisp on the resolution and how a consensus is called within the Github based scenario. I don't think this still adheres to:

> and consensus emerges with little formal voting being required.

Merely coming around to conclusion and final opportunity for objections based on the expected PR. In most scenarios, as outlined above this shouldn't be contentious as the discussion had already been made but is a clear indication of what was resolved allowing people to jump to the last comment and have a solid summary of the expected change and impact. I think all of the above fits within the charter guidelines, just hopefully clarifying the process taking into account the telecon decision from item 1 and the discussions primarily occuring on Github.

> The https://github.com/w3c/media-wg repo, which contains the group's home page, could perhaps be used as central Media WG repo for such pan-specifications discussions.

Thanks, this issue probably should be discussed over there :)

> The public-media-wg@w3.org mailing-list is the only sure way to reach all WG participants in practice: participants are automatically added to the mailing-list when they join the group.

I guess this could be added to the CFC step for a Github issue as I'd expect any telecon minutes with resolutions to go to the mailing list. Worth considering as it does ensure that the group has tried. I think this will also be aided by clarifying in the Github issue the Proposed Resolution so that can be sent to the mailing list assuming this is something the group wants to do in addition. It seems like an easy thing to do as a heads up for any objections.

**Comment by gregwhitworth** [comment]
It seems that we resolved to have monthly calls to keep progress on items. I'm not sure if it was discussed but I would still like very crisp resolutions: - something like this: "Resolved: Remove the specific color space support outlined in the specification". This really helps in reviewing the minutes to find the decisions and make the appropriate edits. I'll go ahead and close this since this was discussed.
