### ISSUE TITLE
EME decodingInfo() - polling for interop support

### ISSUE THREAD

**Issue by chcunningham** [w3c/media-capabilities#140]
@jernoble, @jyavenard, @vi-dot-cpp, 

I'm preparing to send an "intent to ship" to launch the EME features of decodingInfo() in Chrome. Expectations around interop are critical factor for approval to ship, so I'd like to get your thoughts written down here. 

The EME parts have been in the spec for roughly a year with no controversy and no open issues. EME is still defined by the EME spec, MediaCapabilities simply makes a normative reference to an algorithm from requestMediaKeySystem() and various EME types. Here are some handy links!

https://github.com/w3c/media-capabilities/blob/master/explainer.md#encryption
https://w3c.github.io/media-capabilities/#mediacapabilitieskeysystemconfiguration
https://w3c.github.io/media-capabilities/#is-encrypted-decode-supported

Supporting doesn't mean you're obligated to implement right away (but that is of course welcome).

**Comment by chcunningham** [comment]
Also, we have input from Hulu, Youtube and Netflix that this API shape seems sane and works for them.

**Comment by vi-dot-cpp** [comment]
Microsoft Edge votes aye 🚢

**Comment by jernoble** [comment]
This seems fine to me.

**Comment by jyavenard** [comment]
Looks fine to me.
I wish the name MediaCapabilitiesKeySystemConfiguration had been longer though :)

**Comment by chcunningham** [comment]
Thanks everyone!

> I wish the name MediaCapabilitiesKeySystemConfiguration had been longer though :)

Had a good laugh when I read this. It really rolls off the tongue right! The silver lining is that no one (besides us) ever has to type this. Always open to suggestions though.

**Comment by chcunningham** [comment]
Thanks everyone.
