### ISSUE TITLE
*Configuration needs to be subclassed into *DecodingConfiguration

### ISSUE THREAD

**Issue by vi-dot-cpp** [w3c/media-capabilities#146]
Due to additions to AudioConfiguration and VideoConfiguration that only apply to decodingInfo, these classes need to be subclassed into AudioDecodingConfiguration and VideoDecodingConfiguration, respectively. 

cc: @chcunningham @gregwhitworth

**Comment by chcunningham** [comment]
Sounds good. Lets make a list on what to move out. 

Audio: this one's obvious
- boolean spatialRendering

For video its less clear. We recently added these
-  boolean hasAlphaChannel
-  HdrMetadataType hdrMetadataType
-  ColorGamut colorGamut
-  TransferFunction transferFunction

Most of these aren't really decode specific. I'm not aware of any econding pipeline in Chrome that would produce HDR, but maybe one day. 

hasAlphaChannel is weird for encoding. Its weird grammatically, but I also can't think of a practical use. Its easy to imagine an encoding with an alpha channel, but to be useful you'd need to say a lot more about how the alpha channel is constructed (e.g. are you removing the background behind a talking head from a camera stream)? I'd be happy to move this one to decode-only.

**Comment by vi-dot-cpp** [comment]
Thanks for enumerating the items to move out. I think the list makes a lot of sense. Unless anyone objects, I will prepare the change in the upcoming weeks.

**Comment by markafoltz** [comment]
The only properties that are obvious to move an inherited dictionaries are `AudioConfiguration.spatialRendering` and `VideoConfiguration.hasAlphaChannel`.   The HDR related properties may have future use cases for encoding?

I am wondering if it is worth complicating the IDL (and code that relies on it) for two properties.

**Comment by markafoltz** [comment]
After discussion at TPAC, the consensus is to not move in this direction.

https://www.w3.org/2024/09/26-mediawg-minutes.html#t05
