### ISSUE TITLE
Clarify "smooth" for media decoding

### ISSUE THREAD

**Issue by chrisn** [w3c/media-capabilities#155]
The spec currently describes `smooth` as:

> If the user agent is able to decode the media represented by configuration at a pace that allows a smooth playback

which is kind of circular. I suggest clarifying this, similar to the definition we have for media encoding, i.e:

> If the user agent is able to decode the media represented by configuration at a pace that allows decoding frames at the same pace as they are sent to the decoder, set smooth to true. Otherwise set it to false.

**Comment by cconcolato** [comment]
Shouldn't it say "at the framerate indicated in the configuration" and maybe add "without dropping frames"?

**Comment by chrisn** [comment]
I agree, without dropping frames is important.

**Comment by chrisn** [comment]
Here's an updated proposal based on @cconcolato's feedback:
> If the user agent is able to decode the media represented by configuration, at the framerate indicated in the configuration without dropping frames, set smooth to true. Otherwise set it to false.

**Comment by chcunningham** [comment]
Thanks both. This sounds great. I'll send a PR.
