### ISSUE TITLE
Expand support for querying webrtc capabilities

### ISSUE THREAD

**Issue by chcunningham** [w3c/media-capabilities#159]
@jernoble @eric-carlson @jyavenard @padenot @vi-dot-cpp @aboba

Hi group! I'd like to start a discussion around PR #158.

> This PR extends the MediaCapabilities API to the WebRTC use case.
> 
> -Add webrtc to MediaDecodingType
> -Change transmission to webrtc to MediaEncodingType
> -Clarify MIME types for webrtc.
> -Add scalabilityMode to VideoConfiguration.

For some time, encodingInfo() has defined a ["transmission" encoding type](https://w3c.github.io/media-capabilities/#ref-for-dom-mediaencodingtype-transmission) which is roughly an alias for "webrtc". I've raised some concerns (#126) about polishing this area and wanting review/buy-in from WebRTC spec folks. This PR aims to do just that. 

I'm generally supportive
* Expanding support to decodingInfo() makes the API symmetric.
* "webrtc" is more intuitive and future proof than "transmission". The spec currently says that "transmission is used to represent a configuration meant to be transmitted over electronic means (e.g. using RTCPeerConnection as defined in [webrtc])". We shouldn't assume any future api that supports encoding would use the same media pipeline as webrtc.
* scalabilityMode seems like a reasonable hook on the web-rtc SVC spec. chromium is implementing this now.   

Note for discussion: this PR uses different mime type strings when type="webrtc". For ex:
* 'video/VP9;profile-id=0' (as opposed to 'video/webm; codecs="vp09.00.10.08...')
* 'video/H264;profile-level-id=64001f' (as opposed to 'video/mp4; codecs="avc1.64001F"')

The RTC strings come from the IETF SDP definitions. Users would see these strings in the SDP text as well as via APIs like `RTCRtpReceiver.getCapabilities("video")`. 

This difference has been a source of some debate internally. We'd love to hear from other MC implemeters.

**Comment by chcunningham** [comment]
FYI @drkron (PR author, contributor to RTC specs) and @alvestrand (RTC spec expert)

**Comment by aboba** [comment]
If the goal is provide capabilities relevant to WebCodecs, I'd suggest focusing on bitstream capabilities rather than RTP, so as to be generic with respect to transports (e.g. usable with WebTransport as well as RTP).  From a bitstream perspective, this would involve returning the sequence of supported scalabilityMode values supported by the encoder. In VP8/VP9/AV1, a decoder must be able to decode anything an encoder can send. 

WebRTC has its own `getCapabilities()` method for both the `RTCRtpSender` and `RTCRtpReceiver` which includes both bitstream (e.g. codec, scalability modes) and RTP (RTP header extensions, RTCP, etc.) constructs.  Not clear to me that adding RTP capabilities here would add value to WebCodecs (or WebRTC).

**Comment by chcunningham** [comment]
Sorry, I should clarify that this is not related to WebCodecs. The focus of this PR is purely WebRTC. 

> WebRTC has its own getCapabilities() method for both the RTCRtpSender and RTCRtpReceiver which includes both bitstream (e.g. codec, scalability modes) and RTP (RTP header extensions, RTCP, etc.) constructs.

I'll defer to @drkron and @alvestrand to respond on this point.

**Comment by eric-carlson** [comment]
CC @youennf, who may have thoughts on this proposal.

**Comment by drkron** [comment]
Thanks @chcunningham for creating this issue.

From our side, speaking for the Google/WebRTC team, we've seen a need for an API that simplifies the video configuration setup. What we're striving for is an API that enables the client application to select a video configuration even before the call is initiated that is likely to give a good user experience.

I'm looking forward to getting your thoughts on this.

**Comment by youennf** [comment]
In general, there are some redundancies between media capabilities and sender/receiver getCapabilities.
It seems healthy  to try reducing the redundancy, although getCapabilies have shipped for a good amount of time now.

There are some pros for using media capabilities for codec management:
- It would make WebRTC more integrated in the web media platform.
- Media capabilities model is also nicer (async vs sync) and could potentially allow to provide more information.

**Comment by drkron** [comment]
Thanks for your comments @youennf.

The primary reason why I have put this in Media Capabilities is because I prefer the API model of querying a specific configuration rather than listing all supported modes. It's also so similar in structure to the Media Capabilities API so it seemed good to continue building on that, especially since there already is a "transmission" encoding type.

An alternative would be to build something new next to sender/receiver getCapabilities.

What do you think?

**Comment by youennf** [comment]
> especially since there already is a "transmission" encoding type.

It seems there should be a "transmission" decoding type.
I agree the name "transmission" is a bit too generic to my taste, MSE is also transmission somehow.

> An alternative would be to build something new next to sender/receiver getCapabilities.

getCapabilities has some issues, see for instance https://github.com/w3c/webrtc-extensions/issues/49.

> What do you think?

I have a preference to using media capabilities, at least we should try making it happen.

The point raised by @aboba needs to be discussed.
This seems to be something we should discuss during next WebRTC interim meeting.

**Comment by drkron** [comment]
> > An alternative would be to build something new next to sender/receiver getCapabilities.
> 
> getCapabilities has some issues, see for instance [w3c/webrtc-extensions#49](https://github.com/w3c/webrtc-extensions/issues/49).

I'm aware of those issues. I was thinking of a new async API in that case, but I also have a preference to using media capabilities.

> The point raised by @aboba needs to be discussed.
> This seems to be something we should discuss during next WebRTC interim meeting.
That sounds like a great idea. I'll try to join that meeting.

Is there anything I can/should do ahead of the meeting to make sure that the issue is on the agenda?

**Comment by chcunningham** [comment]
The outcome of the WebRTC meeting was supportive of this proposal! The meeting minutes can be found here
https://lists.w3.org/Archives/Public/public-webrtc/2020Dec/0015.html

I'd like to enlist the help of WebRTC WG members (representing other UAs) in completing the review of the attached PR. @ mentioning folks I know
@jan-ivar  @youennf  @aboba 

Particularly on the following points:

**codec string format**
This differs from existing media capabilities strings. It intends to be more familiar/idiomatic for WebRTC authors.

**scalabilityMode**
As described by https://www.w3.org/TR/webrtc-svc/. Chromium has broken ground on implementing this spec, but it seems not a priority (perhaps because SVC support is currently very limited). I don't have enough experience with SVC nor this spec to personally scrutinize the proposal nor gauge it's support from the WebRTC WG.

**Comment by chcunningham** [comment]
@aboba and I chatted over VC. He's approves of including *scalabilityMode* and didn't feel strongly about the *codec string format* (either style would work). 

@jan-ivar @youennf friendly ping for your thoughts on those points.

**Comment by youennf** [comment]
Direction seems good to me. I don't have strong feelings on which string format should be used.
As of scalability mode, I guess this could be added as a follow-up.

**Comment by chcunningham** [comment]
@jan-ivar - one last ping. Hoping to merge this next week. 

> As of scalability mode, I guess this could be added as a follow-up.
@drkron is it important for your use case that this be included sooner than later?

**Comment by drkron** [comment]
> @drkron is it important for your use case that this be included sooner than later?

Both spatial and temporal layers are widely used in video conferencing, and as far as I know the support for spatial layers is very limited in hardware decoders. In Chrome everything that contains spatial layers defaults to software decoding.
So from that perspective scalability mode is needed to be able to respond with a good smoothness value based on whether the video will be decoded in hardware or software.

**Comment by chcunningham** [comment]
Thanks everyone for feedback. If no objection, I'll go ahead and merge this in 24 hours. 

> So from that perspective scalability mode is needed to be able to respond with a good smoothness value based on whether the video will be decoded in hardware or software.

ACK, happy to have it then.

**Comment by chcunningham** [comment]
The PR is now merged. Thanks!
