### ISSUE TITLE
Exposing battery status

### ISSUE THREAD

**Issue by samuelweiler** [w3c/media-capabilities#172]
Breaking this item out from #170.  (@NalaGinrut, for tracking)

2. About the `powerEfficient` field of `MediaCapabilitiesInfo`

> A MediaCapabilitiesInfo has associated supported, smooth, powerEfficient fields which are booleans.
Authors can use powerEfficient in concordance with the Battery Status API [battery-status] in order to determine whether the media they would like to play is appropriate for the user configuration. It is worth noting that even when a device is not power constrained, high power usage has side effects such as increasing the temperature or the fans noise. 

`Question 1:` When the `powerEfficient` is set to `true`, is it possible to expose Battery Status without users' explicit permission?

**Comment by chcunningham** [comment]
> When the powerEfficient is set to true, is it possible to expose Battery Status without users' explicit permission?

No, the intent is that powerEfficient = true/false is independent of the current battery status. It is intended to (very roughly) describe the power draw of a given codec configurations compared to other possible codec configurations on that machine. For example, if your GPU supports H264 acceleration, but not VP9 acceleration, we may say powerEfficient = true and false respectively. But, we may also call VP9 powerEfficient at lower resolutions (say 360p or less) where hardware acceleration does not offer a power savings. Critically, none of these answers would change if you were plugged into a power source.

**Comment by NalaGinrut** [comment]
@chcunningham Thanks, this one is clear and done.
cc @samuelweiler

**Comment by chcunningham** [comment]
Thanks. Please re-open if needed.
