### ISSUE TITLE
Stop initialization if WebRTC is disabled

### ISSUE THREAD

**Issue by samuelweiler** [w3c/media-capabilities#174]
Breaking this item out from #170. (@NalaGinrut, for tracking)

3. The `WebRTC` issue
The `MediaDecodingType` has `WebRTC` option that is used to represent a configuration that is meant to be received using `RTCPeerConnection`. However, `WebRTC` has known privacy issues: https://wiki.mozilla.org/Media/WebRTC/Privacy

`Question:` Is it possible to stop the initialization process if the `WebRTC` was disabled?

**Comment by chcunningham** [comment]
> Is it possible to stop the initialization process if the WebRTC was disabled?

Sorry, which initialization process do you mean?

**Comment by NalaGinrut** [comment]
@chcunningham  My understand is that `MediaConfiguration` is used to initialize the MediaCapabiliies (I may wrong, please correct me). If the encode/decode type in `MediaConfiguration` is `webrtc`, could it be  invalidated if the browser has disabled `webrtc`?

**Comment by chcunningham** [comment]
> My understand is that MediaConfiguration is used to initialize the MediaCapabiliies (I may wrong, please correct me)

I would substitute the word "query" for "initialize". The MC API should not change any state held by the UA. If webrtc is disabled, all queries for webrtc capabilities should come back with supported=false.

**Comment by NalaGinrut** [comment]
@chcunningham Thanks for explaining it! I think this one is clear and done.
cc @samuelweiler

**Comment by chcunningham** [comment]
Thanks!
