### ISSUE TITLE
Split security and privacy considerations

### ISSUE THREAD

**Issue by samuelweiler** [w3c/media-capabilities#175]
The security and privacy considerations for the spec should be split, as documented in the current version of https://w3ctag.github.io/security-questionnaire/.

(This is not a blocking issue, though I would appreciate the editors resolving it.)

**Comment by chcunningham** [comment]
Ack, will do.

**Comment by samuelweiler** [comment]
We have changed the guidance, and while separate security and privacy sections are still recommended, they are not required.  Feel free to close this issue or not, as you prefer.

**Comment by chrisn** [comment]
Sorry for the late follow up, and thanks @samuelweiler. I'll close this if the change isn't required, but we can always split them later if it makes sense editorially when making changes to this section.
