### ISSUE TITLE
meaning of MediaDecodingType "file" is unclear

### ISSUE THREAD

**Issue by jpiesing** [w3c/media-capabilities#184]
The meaning of MediaDecodingType = "file" is unclear.

![image](https://user-images.githubusercontent.com/8490792/142004129-45d3fc55-231b-4068-b761-7181a6d083a0.png)

Some people interpreted this as meaning file: URLs, i.e. files on the local storage.
Others (myself included) interpret (hope) that it covers all playback where the src of the media element is an http / https URL, or indeed any URL except for one resulting from createObjectURL(mediaSource).

Please clarify what MediaDecodingType "file" is meant to mean & improve the wording, at least add some examples.

The reason for hoping MediaDecodingType "file" means covers a video element whose src is http or https is that this enables the media query API to test what is supported when implementations support different codecs with and without MSE. 

Thank you.

**Comment by chcunningham** [comment]
Happy to add some clearer text and examples for this.

> Others (myself included) interpret (hope) that it covers all playback where the src of the media element is an http / https URL, or indeed any URL except for one resulting from createObjectURL(mediaSource).

This is the intended meaning. 

> The reason for hoping MediaDecodingType "file" means covers a video element whose src is http or https is that this enables the media query API to test what is supported when implementations support different codecs with and without MSE.

Should work exactly as you hoped.
