### ISSUE TITLE
Replace ColorGamut and TransferFunction with VideoColorSpace?

### ISSUE THREAD

**Issue by dalecurtis** [w3c/media-capabilities#205]
I just noticed that no UA has yet shipped HDR media capabilities.

Is it too late to replace the bespoke primaries and transfer function names with the ones in WebCodecs? I.e., either replace them entirely with `VideoColorSpace` or individually we'd replace (and likely rename):
* `ColorGamut` with `VideoColorPrimaries`
* `TransferFunction` with `VideoTransferCharacteristics`

Current enums:
```
enum ColorGamut { "srgb", "p3", "rec2020" };
enum TransferFunction { "srgb", "pq", "hlg" };
```

WebCodecs ones:
```
// https://www.w3.org/TR/webcodecs/#videocolorprimaries
enum VideoColorPrimaries {
  "bt709",      // BT.709, sRGB
  "bt470bg",    // BT.601 PAL
  "smpte170m",  // BT.601 NTSC
  "bt2020",     // Also BT.2100
  "smpte432",   // P3 D65
};

// https://www.w3.org/TR/webcodecs/#videotransfercharacteristics
enum VideoTransferCharacteristics {
  "bt709",         // BT.709
  "smpte170m",     // BT.601 (functionally the same as bt709)
  "iec61966-2-1",  // sRGB
  "linear",
  "pq",            // BT.2100 PQ
  "hlg",           // BT.2100 HLG
};

interface VideoColorSpace {
  constructor(optional VideoColorSpaceInit init = {});

  readonly attribute VideoColorPrimaries? primaries;
  readonly attribute VideoTransferCharacteristics? transfer;
  readonly attribute VideoMatrixCoefficients? matrix;
  readonly attribute boolean? fullRange;

  // Note: [Default] implementation would be correct.
  VideoColorSpaceInit toJSON();
};
```

@jernoble @padenot @gregwfreedman

**Comment by Djuffin** [comment]
TPAC 2023 Media WG meeting. Greg Freedman says it's implemented in Safari.

**Comment by dalecurtis** [comment]
Ah, I couldn't get it to work. Searching the code I just see this:
https://github.com/WebKit/WebKit/blob/main/Source/WebCore/platform/graphics/cocoa/VP9UtilitiesCocoa.mm#L257

Which just seems to validate the codec string matches the color space selected. @jernoble @youennf can you confirm this is implemented? If so we can abandon this suggestion.

**Comment by padenot** [comment]
It looks implemented, e.g. https://searchfox.org/wubkat/search?q=ColorGamut&path=&case=false&regexp=false (this is an index of WebKit with cross-references etc., kept up to date).

**Comment by dalecurtis** [comment]
Seems no interest in changing this so closing as WontFix.
