### ISSUE TITLE
Throw type error when the configuration in MediaDecodingConfiguration doesn't match the one in keySystemConfiguration

### ISSUE THREAD

**Issue by alastor0325** [w3c/media-capabilities#220]
In current web platform tests, there are some [test cases](https://searchfox.org/mozilla-central/rev/46d0387f0b582f00a5722c20d4e6b8693793631b/testing/web-platform/tests/media-capabilities/decodingInfoEncryptedMedia.https.html#77-117) used to check whether the configuration of [MediaDecodingConfiguration](https://w3c.github.io/media-capabilities/#dictdef-mediadecodingconfiguration) matches the configuration of [keySystemConfiguration](https://w3c.github.io/media-capabilities/#dom-mediadecodingconfiguration-keysystemconfiguration), but those checks aren't mentioned in the spec at all.

If the type error should be raised when the configuration doesn't match, we should add new steps to perform the check in [decodingInfo()](https://w3c.github.io/media-capabilities/#dom-mediacapabilities-decodinginfo) or [2.3.2. Create a MediaCapabilitiesDecodingInfo](https://w3c.github.io/media-capabilities/#create-media-capabilities-decoding-info).

**Comment by chrisn** [comment]
Thanks @alastor0325. I agree this would be good to add to the spec. The requirement seems to be:

* If `configuration.keySystemConfiguration.audio.robustness` is present, then `configuration.audio` must also be present
* If `configuration.keySystemConfiguration.video.robustness` is present, then `configuration.video` must also be present

WPT shows that Safari doesn't have these checks. @jyavenard, @marcoscaceres, is this OK with you?

**Comment by markafoltz** [comment]
The steps to check for a [valid MediaConfiguration](https://w3c.github.io/media-capabilities/#valid-mediaconfiguration) already check for the existence of the corresponding `MediaConfiguration` for a given `keySystemConfiguration`.    This can be closed.
