### ISSUE TITLE
Distinguish graphics and video capabilities

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-capabilities#25]
Output size, colour gamut and various other properties can be very different between graphics and video. This is very common for devices such as TV. At the moment, the Web Platform is totally unaware of this specificity. We should look at an overall approach to handle these devices.

It doesn't have to be done as part of this specification but it definitely affects the work we are doing here so we should think about it later.

**Comment by mwatson2** [comment]
I think this is addressed by the current proposal PR #124 and we should close this issue.

**Comment by chcunningham** [comment]
The consensus around this shifted, and these parts were removed the PR. We do have other issues to track the remaining work with more recent discussion. @mwatson2, just want to double check with you - ok to close this and continue the discussion in #133 and #135?

**Comment by mwatson2** [comment]
@chcunningham Yup, ok to continue the discussion there. Good to de-dup the issues.
