### ISSUE TITLE
Need a mechanism for considering device conditions that affect media capabilities

### ISSUE THREAD

**Issue by jdsmith3000** [w3c/media-capabilities#43]
I noted issue #26 talked about environment, but then converged very specifically on dealing with scenarios where capabilities can change (e.g. when the display suddenly changes or is sent to a remote screen).  There are also situations where steady considerations will affect the query response.

Some:

- An EME *keySystem* can represent a software media pipeline or one that is in hardware.  The capabilities of each would likely be quite different.
- If a device is *batteryPowered* or not could affect the response.  It's perhaps more likely that it would do so based on policy rather than a hard difference in capabilities between battery and AC power.  Given the power consumed by very high quality video streams, users may wish to play HD content only on battery.  Designs should be able to reflect this in the capabilities queries.

There could be others.  I'd like to see some provision to include conditions along with audio and video configurations, perhaps as a MediaConditions addition to MediaConfiguration?

dictionary MediaConfiguration {
  VideoConfiguration video;
  AudioConfiguration audio;
  MediaConditions conditions;
};

**Comment by chcunningham** [comment]
Working on adding key systems to the query. [Explainer](https://github.com/WICG/media-capabilities/blob/master/explainer.md#encryption) was updated a while back. [Pull request](https://github.com/WICG/media-capabilities/pull/101) posted recently.

No work done on the battery request. How would sites use this? They may learn that capabilities differ when unplugged, but have no way of knowing whether the user is planning to unplug. Users who don't unplug during the playback will not want sites to take the min(plugged, unplugged) capabilities.

**Comment by marcoscaceres** [comment]
We looked the issue and have concluded to close it as no further action is needed here.
