### ISSUE TITLE
powerEfficient needs some objective definition

### ISSUE THREAD

**Issue by jdsmith3000** [w3c/media-capabilities#44]
The powerEfficient attribute currently is open ended, so it would be difficult to have multiple UAs respond similarly.  I'm not sure how it can be objectively defined, but that seems needed.

**Comment by mounirlamouri** [comment]
I guess the specification could be a bit more verbose. I think we could mention something like having a low power cost to the system and mention that for example, hardware accelerated decoding might often end up in that bucket but not only. We expect to have some UA logic here and maybe getting implementation feedback might help understand the various signals being used.

**Comment by chcunningham** [comment]
How about something like this:
_Decoding is power efficient when it uses hardware acceleration or when the power usage for a non-accelerated codec is roughly equivalent to that of available accelerated codecs for the given framerate and resolution._ 

For example: say a given machine has hardware accelerated AVC main profile decode, but does not have hardware accelerated VP9 decode. In this case, queries for AVC main should generally return powerEfficient = true (exceptions include outlier stream configurations that hw decoder may not support - e.g. extremely high resolution). For this same machine, queries for VP9 should generally return powerEfficient = false, but may return powerEfficient = true for resolutions/framerates below a threshold (e.g. 240p@24fps) where lab testing has shown negligible differences in power draw vs comparable AVC configurations. 

This reasoning is based on my interpretation of the use case for the powerEfficient field. When web authors compare this value between stream configurations (codecs, resolutions, etc), they are seeking to know what configurations conserve power _for your particular machine_. This motivates a definition that describes efficiency of software codecs _relative to available hardware codecs_. If we instead defined power efficient in terms of some wattage threshold we will often break this use case whenever a given hardware decoder doesn't meet the bar (in spite of it still drawing a fraction of the power used by software codecs at higher resolutions). Moreover, it is not feasible to even know the the exact power draw for all types of video decode over the long tail of devices UAs ship on.

The definition proposed above is admittedly still vague, but I think its practical for UAs and useful to web authors.

**Comment by mounirlamouri** [comment]
I think your definition would be an improvement over what the spec says but I wonder if we could be a bit more generic. Something like:
_Decoding is power efficient when the power draw is optimal or close to optimal. The definition of optimal power draw from decoding is left to the user agent but common implementation strategies would be to consider hardware decode as optimal power draw. It is NOT RECOMMENDED to only mark as power efficient hard decoding as power draw decoding of non-accelerated codec can sometimes be very close to accelerated ones (for example, low resolution videos)._
