### ISSUE TITLE
MediaCapabilitiesInfo doesn't indicate what configuration it represents

### ISSUE THREAD

**Issue by bzbarsky** [w3c/media-capabilities#82]
Given a `MediaCapabilitiesInfo`, it's not possible to tell what configuration query resulted in the object.  That makes it more complicated to query multiple different configurations, because you now have to keep track of which returned Promise belongs with which configuration.

Even the spec itself gets this wrong: the example in section 5.1 uses `result.contentType`, but `result` is a `MediaCapabilitiesInfo` and doesn't have a `.contentType` property.

**Comment by mounirlamouri** [comment]
Thanks for the feedback. @joeyparrish, was this an issue you experimented with the implementation in Shaka?

**Comment by jyavenard** [comment]
I believe that the missing contentType attribute on MediaCapabilitiesInfo is more than just ergonomics, in particular as it makes section 5.1 example invalid.

the contentType attribute should be added to MediaCapabilitiesInfo and populated to what queried decodingInfo/encodingInfo.

The leads to also the following: I don't think there's any points in performing a check for both audio and video at once. I can't think of a case where a combination of audio/video could make a difference to say video config alone.

And that complicates the passing of contentType to MediaCapabilitiesInfo.

So maybe MediaConfiguration should contains either audio or video, not both.

If both is really wanted, then MediaCapabilitiesInfo should also separate the result for audio and/or video.

**Comment by mounirlamouri** [comment]
I wouldn't say that making example 5.1 invalid is a reason sufficient to add `contentType` to the interface. It's a hint that maybe developers expect it.

Having separate results for audio and video seems counter intuitive as the idea is for a website to be able to ask if a particular configuration is supported. Splitting the result would require them to do the merge themselves. What would be the benefits? Is this only to make `contentType` easier to integrate?

**Comment by mounirlamouri** [comment]
`isTypeSupported()` is for MSE but this API was also designed to replace `isTypeSupported()` and `canPlayType()`. I think having the flexibility to ask for a pair of A/V isn't a bad thing and adds no burdens to the general ergonomics (except for simply offering a `contentType` in the returned object).

This said, we could easily simply offer the input dictionary as part of the returned object if that's something developers want. My initial instinct is that it's easy to bind and some applications may even want to bind their own stuff instead so I want to make sure there are strong use cases if we do this.

**Comment by mounirlamouri** [comment]
As far as I can tell, looking at YouTube's code, they bind their own internal configuration representation to the call. I would expect most applications to have something similar. For example, Shaka probably has a representation of a configuration based on DASH and I wouldn't be surprised if they simply bind it for the calls.

**Comment by joeyparrish** [comment]
Sorry I missed the email when you tagged me.  We haven't started adding MC to Shaka Player yet, but I'm getting started now.  I think binding our `Stream` object to the callback or closing over the `Stream` object makes sense.  I'll let you know how it goes once I've tried it out.

**Comment by joeyparrish** [comment]
No issues with this for me.  I'm doing a filter that looks like roughly this:

```js
isVariantSmooth = async function(variant) {
  if (!navigator.mediaCapabilities) {
    // No MediaCapabilities API?  Don't restrict our choices at all.
    return true;
  }

  const mediaConfig = ...;
  const result = await navigator.mediaCapabilities.decodingInfo(mediaConfig);
  return result.supported && result.smooth;
};

filterPeriodForSmoothness = async function(period) {
  // Get smoothness results for all variants asynchronously, in parallel.
  const results = await Promise.all(period.variants.map((variant) => {
    return isVariantSmooth(variant);
  }));

  // Now filter the array with those results.
  const filtered = period.variants.filter((variant, index) => results[index]);

  console.debug(period.variants.length + ' variants in the period, ' +
                  'of which ' + filtered.length + ' are smooth.');

  // Use the smooth variants, if there are any.
  if (filtered.length) {
    period.variants = filtered;
    return;
  }

  // If none are smooth, keep the lowest resolution only.
  const heights = period.variants.map((variant) => variant.height);
  const minHeight = Math.min.apply(null, heights);
  period.variants = period.variants.filter(
      (variant) => variant.height == minHeight);
};
```

At least the way I'm doing things, it's fairly easy to keep up with which result goes with what input.

I am running into one issue with the implementation in Chrome, which I will file separately.

**Comment by bzbarsky** [comment]
Right, the code above depends on the indexing of the `period` array matching that of the `results` array (which it does) and not needing to do anything with any of the results until all the results are in.  This second constraint is not necessarily something that applies to all consumers, though.

**Comment by joeyparrish** [comment]
Of course, YMMV, and everyone may want to use it differently.

Could you post some sample code showing what makes it challenging to match results to specific queries?  Sometimes it's much easier to understand the difficulty of an API with a snippet.

**Comment by bzbarsky** [comment]
It's not necessarily challenging.  It's just extra bookkeeping you end up having to do.

But here's a concrete question: can you be in a situation where you make some decoding info queries and act on the first one that comes back, whichever one that is?  Because doing that while keeping the mapping is a bit of a pain as far as I can tell.

**Comment by mounirlamouri** [comment]
I agree that it would be a pain, though I can't think of a valid use case that would require to do this. Racing Media Capabilities calls wouldn't be a very wise thing to do especially because the calls should be fast and we don't expect callers to be that much time sensitive.

This said, I want to clarify the position: I think we should consider doing this but I think this is ergonomics and we would expect a lot of users to simply bind some object like YouTube or Shaka do. We could easily add the input in the response object but this can make some future changes we are thinking of harder. For example, one idea that is in the explainer is to offer some chaining in which case the input would be an array.

To take a step back, I'm only aware of the EME API that gives back the input when responding to a request. I can't think of an async API that follow this pattern even recent and common APIs like fetch. Am I looking at the wrong APIs or is there something specific to this one that makes this problem more concerning?

**Comment by bzbarsky** [comment]
I don't think there's anything specific to this API per se; it's something to worry about for async APIs in general.

For fetch specifically, racing definitely doesn't make sense, and more importantly for fetch you can tell what you have based on the response what you have (e.g. the response has a URL identifying it).  In partiular, you don't need to know the input (the original URL being fetched) to do something useful with a fetch result.  For this API, you _have_ to know the input to make any sense of the result, no?

**Comment by chcunningham** [comment]
We've recently agreed to add the configuration to the returned info in #111
