### ISSUE TITLE
Consider making MediaCapabilities a member of media element instead of navigator

### ISSUE THREAD

**Issue by jyavenard** [w3c/media-capabilities#86]
Currently, to request a MediaCapabilitiesInfo you retrieve the mediaCapabilities from navigator (or workerNavigator).

This makes some sense if you consider that you want to know what this particular machine can play *overall*.

However, it would make more sense to query a particular video (or audio) element on what it can play, and how it can play it.

A video element inherently knows more about context than the navigator ever could: it knows about its current status. It knows at which position it is displayed (and as such, which monitor and graphic card is used), the display size it is currently using etc...

We can imagine a video element being displayed on an external USB screen, for which HW decoding isn't available.

I came into this problem while implementing MediaCapabilities and having to decide which graphic card  to query to determine how well we could do a particular codec. That decision can't be made when MediaCapabilities is attached to navigator.

Of course those conditions can change, and having mediaCapabilities on the media element also allows for a much easier way to deal with those changes (such as firing an event at the mediaCapabilities); and I'm hoping changing of MediaCapabilitiesInfo is something that will be addressed soon.

As such, I propose the MediaCapabilities webIDL to add (or be changed to):

[Exposed=(Window)]
partial interface HTMLMediaElement {
  [SameObject] readonly attribute MediaCapabilities mediaCapabilities;
};

**Comment by PauKerr** [comment]
From my perspective, this will also help solve the issue, brought up in other issue threads  (#53), of determining to which physical display of a multi-display system, for example, a laptop connected to a HDR capable monitor, the capabilities query is targeted. As it stands now, the agent may return a capability that is suited to the most capable display but this gives no guidance to the client as to which window to create the <video> element.

**Comment by chcunningham** [comment]
Woot for MC in Firefox! 

> it knows about its current status. It knows at which position it is displayed (and as such, which monitor and graphic card is used), the display size it is currently using etc...

This doesn't hold for media elements that are not attached to the dom. Also, in chrome the rendred position and size generally do not determine decoding performance - encoded size is the more critical factor. 

> We can imagine a video element being displayed on an external USB screen, for which HW decoding isn't available.

I'm confused here. In Chrome we do not consider the output screen when selecting a decoder, including possibly selecting hardware accelerated decoders. Why does having a USB prevent using the HW decoder?

> I came into this problem while implementing MediaCapabilities and having to decide which graphic card to query to determine how well we could do a particular codec. That decision can't be made when MediaCapabilities is attached to navigator.

We also don't "decide which graphics card". HW decoding is facilitated by various OS APIs that abstract that detail, and AFAIK these also are not gated on use of a particular screen. Can you explain how this works in FF? 

> Of course those conditions can change, and having mediaCapabilities on the media element also allows for a much easier way to deal with those changes (such as firing an event at the mediaCapabilities); and I'm hoping changing of MediaCapabilitiesInfo is something that will be addressed soon.

Will wait to comment on this. I agree capabilities can change, but its not clear yet how screen choice impacts *decoding* abilities. 

Aside: I don't think we have any open issues on changing capabilities atm. Its something on the horizon, but I'm not actively working on it and its not clear that it will be handled here vs some other API (e.g. VideoPlaybackQuality).

> From my perspective, this will also help solve the issue, brought up in other issue threads (#53), of determining to which physical display of a multi-display system,...

I'll reply separately on that bug. I agree it helps with your proposal in #53, but there are other more significant obstacles to implementing that proposal.

**Comment by jyavenard** [comment]
If the media element isn't attached to the DOM, then it can play everything smoothly and extremely efficiently can it not ? :) after all, you can then ignore the video track if any.

Abstractly, what you care about is what the element itself can play. Just like canPlayType is a method of the media element itself, and isTypeSupported a method of the MediaSource.
In continuity, and accepting that MediaCapabilities is an extension (and potentially a replacement as per issue #3 ) of canPlayType, it seems more logical to have it attached to the media element.
I would expect an audio element to states that it can't play any video.

It also facilitates currently missing (yet important IMHO) features of MediaCapabilities: that is EME related capabilities.
If a CDM/MediaKeys is attached to the media element, you can now expect MediaCapabilities to take this into account, resolving issue #47 nicely.
It also helps issue #43 because the media element knows that information too.

Having MediaCapabilities attached to navigator provides no advantage over it being an attribute of the media element.

Other than this is how Chrome implemented it, what could the navigator provides that the media element can't?

To answer your question about HW decoding facility, 
As an example: I have a dual GPU system, one with a nvidia card this has a native VP9 decoder, and another AMD Vega: the vega doesn't have a native vp9 decoder. You can do HW decoding on the nvidia via the Microsoft VP9 MFT while you can't on the vega. The MediaCapabilitiesInfo would be significantly different between the two.
Some USB graphic card works like that.

That last example isn't entirely relevant to the discussion at hand, I was just using it as an argument of what you could potentially distinguish if you were to attach MediaCapabilities to the media element, while you can't if it's with navigator.

MediaCapabilities implementation is still being discussed, so this is our proposal ...

**Comment by chcunningham** [comment]
> If the media element isn't attached to the DOM, then it can play everything smoothly and extremely efficiently can it not ? :) after all, you can then ignore the video track if any.

:) I don't know if that holds up. By extension, it seems an unattached \<video\> should report "probably" for literally any mime type. Probably not what users expect. 

More practically, elements that aren't attached can still be used to create video frames webGL / canvas. Timely decoding is important for that use case. 

> Abstractly, what you care about is what the element itself can play. Just like canPlayType is a method of the media element itself, and isTypeSupported a method of the MediaSource.
In continuity, and accepting that MediaCapabilities is an extension (and potentially a replacement as per issue #3 ) of canPlayType, it seems more logical to have it attached to the media element.

I agree HTMLMediaElement::canPlayType() spec requires an instance, but MediaSource.isTypeSupported() is just a static method. FWIW, Chrome's implementation of canPlayType() is essentially static - it does not use any information about the element it's called on.

> I would expect an audio element to states that it can't play any video

\<audio\> can't render video, but IMO that's not something this API needs to document.

Aside: in both Chrome and Firefox 
document.createElement('audio').canPlayType('video/webm; codecs="vp9"') == "probably". This is a weird edge case, but Chrome really does "play" such content - you just don't see the video painted. 

> If a CDM/MediaKeys is attached to the media element, you can now expect MediaCapabilities to take this into account, resolving issue #47 nicely.

EME is super important, but this proposal doesn't resolve #47. EME users want to learn what the browser can do _before_ they start setting up a playback (e.g. making round trips to a license server). For example, see the [HDCP proposal](https://github.com/WICG/hdcp-detection/blob/master/explainer.md), which is all about surfacing more info up-front. 

Also, it is often not possible to configure a single \<video\> with a MediaKeySystemConfiguration that describes all possible streams the site may have available (e.g. a configuring a CDM to use codec X and robustness A may often preclude using codec Y with robustness B). 

My latest thinking on supporting EME is [here](https://github.com/WICG/media-capabilities/blob/master/explainer.md#encryption). Feedback welcome!

> I was just using it as an argument of what you could potentially distinguish if you were to attach MediaCapabilities to the media element, while you can't if it's with navigator.

I follow the setup here, but I want to respectively poke at it more. 2 cards may have different capabilities, but I don't think choosing a screen forces you to use a certain card. The decoded output from the MFT goes to a buffer than can be rendered on any screen.

**Comment by jyavenard** [comment]
The HTML5 spec specifically states that a non attached video element should only be playing audio.
"Media elements that are potentially playing while not in a document must not play any video, but should play any audio component. Media elements must not stop playing just because all references to them have been removed; only once a media element is in a state where no further audio could ever be played by that element may the element be garbage collected."
https://html.spec.whatwg.org/multipage/media.html

For EME, EME provides tools to determine what encryption is supported by the user agent. I believe those tools are sufficient as they are, and we shouldn't attempt to write yet another mechanism to determine that. If something needs to be added to better detect encryption support, I believe that it should be done within EME spec, not create a new one (even in MediaCapabilities) to get around flaws in the first.

The flow should be:
Use EME tools to determine what is supported
Attach MediaKeys to video element.
Query video element on what it can do with that information and if it can do it well.

But all of the above is out of topic, again I was only pointing area where having MediaCapabilities attached to the media element would help resolve addressing some potential problems, and directly help in implementation by bypassing some technical problem.

Having MediaCapabilities attached to navigator provides no advantage of any kind. I don't believe it should live there.

**Comment by chcunningham** [comment]
Obsolete.
