### ISSUE TITLE
change event definition is way too broad

### ISSUE THREAD

**Issue by bzbarsky** [w3c/media-capabilities#89]
The spec draft says:

> Whenever the user agent is aware that the state of the Screen object has changed, that is if one the value exposed on the Screen object or in an object exposed on the Screen object, it MUST queue a task to fire an event named change on Screen. 

That has a very significant comefrom/monkeypatch smell.  It requires that a change event be fired when any property defined by any specification on the Screen object changes.  I doubt that's what's intended, and it's _very_ unlikely that it's what implementations are planning to do.

If the intent is to have an event fire when the properties defined by this specification change, the text should say so and the event should have a corresponding name.

If the intent is really to have this event fire when any property of Screen changes, then we need to have a conversation about whether that's a reasonable thing to do and how to actually specify that sanely.

**Comment by bzbarsky** [comment]
Oh, and the current definition sounds like if the min and max luminance both change at once there will be two events.  That seems odd.

**Comment by mounirlamouri** [comment]
This part of the spec isn't finished, see #76

**Comment by bzbarsky** [comment]
OK.  I got here because people were implementing it (or trying to and failing).

**Comment by chcunningham** [comment]
change event is removed in #124
