### ISSUE TITLE
What task source is used for change event tasks?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/media-capabilities#90]
The spec says to queue a task, but not what task source to use.

**Comment by mounirlamouri** [comment]
I'm thinking of dropping the task queuing here as it doesn't seem necessary. WDYT?

**Comment by bzbarsky** [comment]
How is it not necessary?  The event needs to fire from _some_ task.  The "we noticed a change" thing is not happening in a task; it's an out-of-band thing of some sort the browser is doing.

**Comment by chcunningham** [comment]
Events were removed in #124
